$s2madir = "./s2ma"
$tempdir = "./_temp_"
$mapdir = "./maps"
$moddir = "./mods"
$mpqesitor = "./MPQEditor.exe"


New-Item -ItemType Directory -Force -Path $s2madir | Out-Null

New-Item -ItemType Directory -Force -Path $tempdir | Out-Null
New-Item -ItemType Directory -Force -Path $mapdir | Out-Null
New-Item -ItemType Directory -Force -Path $moddir | Out-Null

Get-ChildItem -Path $tempdir -Include * -File -Recurse | ForEach-Object { $_.Delete() }
Get-ChildItem -Path $mapdir -Include * -File -Recurse | ForEach-Object { $_.Delete() }
Get-ChildItem -Path $moddir -Include * -File -Recurse | ForEach-Object { $_.Delete() }

$mpqesitor = Resolve-Path $mpqesitor
$s2madir = Resolve-Path $s2madir
$tempdir = Resolve-Path $tempdir



$markdown = @"
# ``*.s2ma`` Tables

The tables are generated by [``renamer.ps1``](https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/renamer.ps1).

- [Full Table](#table-full)

- [Maps only Table](#table-maps)

- [Mods only Table](#table-mods)

- [Null only Table](#table-null)


<a name="table-full" />

## Full Table

| s2ma | type | path |
 |-|-|-|
"@

$markdownMapsTable = @"

---
<a name="table-maps" />

## Maps only Table

This table only contains the Map files:

| Map Name | s2ma |
|-|-|
"@

$markdownModsTable = @"

---
<a name="table-mods" />

## Mods only Table

This table only contains the Mod files:

| Mod Name | s2ma |
|-|-|
"@

$markdownNullTable = @"

---
<a name="table-null" />

## Null only Table

This table only contains the Null files (Undecided Files):

| s2ma |
|-|
"@

function getModName ($file) {
	# Full path of the s2ma file
	$filePath = $file.FullName 
	# Basename (without extension) of the s2ma file
	$basename = $file.BaseName

	$temppath = ($tempdir.Path + "\" + "$basename")

	# Extract the GameStrings.txt
	Start-Process $mpqesitor -ArgumentList "extract", "$filepath", "enus.stormdata/localizeddata/gamestrings.txt", "$temppath" -NoNewWindow -PassThru | Wait-Process

	# Read the extracted file
	if (Test-Path -Path ($temppath + "\" + "gamestrings.txt")) {
		$DocInfoName = Get-Content -Path ($temppath + "\" + "gamestrings.txt") | Select-String -Pattern "^DocInfo/Name="
		# $DocInfoName = $DocInfoName.Replace("DocInfo/Name=", "")
		$DocInfoName = $DocInfoName.ToString().Replace("DocInfo/Name=", "").Replace(":", "")
		return $DocInfoName
	}
 else {
		return $false
	}
}

function isMapFile($file) {
	# Full path of the s2ma file
	$filePath = $file.FullName 
	# Basename (without extension) of the s2ma file
	$basename = $file.BaseName

	$temppath = ($tempdir.Path + "\" + "$basename")

	Start-Process $mpqesitor -ArgumentList "extract", "$filepath", "mapscript.galaxy", "$temppath" -NoNewWindow -PassThru | Wait-Process

	return Test-Path -Path ($temppath + "\" + "mapscript.galaxy")
}

# Loop each file

Get-ChildItem -File -Path $s2madir -Filter "*.s2ma" | Sort-Object | ForEach-Object -Process {
	
	$isS2MAMapFile = isMapFile($_)
	$ModName = getModName($_)

	if ($ModName) {

		if ($isS2MAMapFile) {
			# Its a stormmap file, copy to ./maps and rename it
			Copy-Item $_.FullName -Destination "$mapdir/$ModName.stormmap" -Force
			$markdown = $markdown + "`n| [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_"))) | ``Map`` | [``./maps/$ModName.stormmap``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/tree/main/maps/$ModName.stormmap"))) |"
			$markdownMapsTable = $markdownMapsTable + "`n| [``$ModName``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/tree/main/maps/$ModName.stormmap"))) | [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_")))|"

		}
		else {
			# Its a stormmod file, copy to ./mods and rename it
			Copy-Item $_.FullName -Destination "$moddir/$ModName.stormmod" -Force
			$markdown = $markdown + "`n| [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_"))) | ``Mod`` | [``./mods/$ModName.stormmod``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/tree/main/mods/$ModName.stormmod"))) |"
			$markdownModsTable = $markdownModsTable + "`n| [``$ModName``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/tree/main/mods/$ModName.stormmod"))) | [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_"))) |"
		}
		
	} else {
		$markdown = $markdown + "`n| [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_"))) | ``Null`` | ``Null`` |"
		$markdownNullTable = $markdownNullTable + "`n| [``$_``]($([uri]::EscapeUriString("https://github.com/jamiephan/HeroesOfTheStorm_S2MA/blob/main/s2ma/$_"))) |"
	}

}

# Clean up Temp dir
Remove-Item -Recurse $tempdir

# Copy maps from extra_maps to maps
Copy-Item -Path "./extra_maps/*.stormmap" -Destination $mapdir -Recurse

# Save the markdown file
$markdown = $markdown + "`n" + $markdownMapsTable + "`n" + $markdownModsTable + "`n" + $markdownNullTable
Out-File -FilePath "./TABLE.md" -InputObject $markdown

