name: Automatically Fetch S2MA Files
on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  auto-fetch-s2ma:
    name: Automatically Fetch S2MA Files
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
      - name: git config
        run: |
          git config --global user.name 'Jamie Phan'
          git config --global user.email '9488815+jamiephan@users.noreply.github.com'
      - name: Running "npm run ci"
        run: |
          npm install
          npm run ci
